require(graphics)
file<-read.table("e:/PHD_work/STRING/Hallmark enrichment/enrichment matrix(p).txt",header=F,sep="\t")
file1<-as.matrix(file)
distance_matrix<-dist(file1,method = "euclidean", diag = FALSE, upper = FALSE, p = 2)
hc<-hclust(distance_matrix,method="complete")
plot(hc,hang=-1,cex=.8,xlab="Lymphatic Invasion Patients(n=142)",ylab="Similarity distance score")
re<-rect.hclust(hc,k=2)
id<-cutree(hc,2)
write.table(id,"e:/PHD_work/STRING/Hallmark enrichment/clusterID_res(p-2class).txt",sep="\t",col.names=F,row.names=F,quote=F)
library("gplots")
library(RColorBrewer)
col <- colorRampPalette(brewer.pal(10, "RdYlBu"))(10)
heatmap.2(as.matrix(distance_matrix),cexRow=0.4,cexCol=0.4,col=col,key=T,symkey=F,density.info="none",trace="none",scale="none")
heatmap.2(file1,cexRow=0.4,cexCol=0.7,col=col,key=T,symkey=F,density.info="none",trace="none",scale="none")


cluster<-read.table("e:/PHD_work/STRING/Hallmark enrichment/clusterID_res(p-2class).txt",header=F,sep="\t")
cluster1<-as.matrix(cluster)
fre<-table(cluster1[,2])
write.table(fre,"e:/PHD_work/STRING/Hallmark enrichment/subtype_fre.txt",sep="\t",col.names=F,row.names=F,quote=F)